
name: interviewmate-platform

include:
  # -------- Core Infra --------
  - docker-compose.infra-ai.yml

  # -------- Ai Services --------
  - InterviewQuestionService\docker-compose.interview-question.yml
  - VideoAudioSeperatorService\docker-compose.video-audiio-seperator.yml
  - AudioAnswerConverterService\docker-compose.audio-answer-converter.yml
  - BehavioralAnalysisService\docker-compose.behavioral-analysis.yml
  - InterviewReportService\docker-compose.interview-report.yml
  - Client\docker-compose-client.yml