services:
  - type: web
    name: ResumeService
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y portaudio19-dev
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT